import type { Language } from '../i18n';
export const symptomTranslations: Record<Language,string[]> = {
 cs:['Bolí mě hlava.','Bolí mě břicho.','Bolí mě na hrudi.','Bolí mě zub.','Špatně se mi dýchá.','Mám horečku.','Zvracím.','Mám průjem.','Krvácím.','Upadl/a jsem a zranil/a jsem se.','Mám alergickou reakci.','Užívám léky.','Potřebuji lékaře.','Točí se mi hlava.','Bolí mě záda.'],
 en:['I have a headache.','My stomach hurts.','I have chest pain.','I have a toothache.','I have difficulty breathing.','I have a fever.','I am vomiting.','I have diarrhea.','I am bleeding.','I fell and injured myself.','I am having an allergic reaction.','I take medication.','I need a doctor.','I feel dizzy.','My back hurts.'],
 de:['Ich habe Kopfschmerzen.','Ich habe Bauchschmerzen.','Ich habe Brustschmerzen.','Ich habe Zahnschmerzen.','Ich habe Atemnot.','Ich habe Fieber.','Ich muss mich übergeben.','Ich habe Durchfall.','Ich blute.','Ich bin gestürzt und habe mich verletzt.','Ich habe eine allergische Reaktion.','Ich nehme Medikamente.','Ich brauche einen Arzt.','Mir ist schwindelig.','Ich habe Rückenschmerzen.'],
 it:['Ho mal di testa.','Mi fa male la pancia.','Ho dolore al petto.','Ho mal di denti.','Ho difficoltà a respirare.','Ho la febbre.','Sto vomitando.','Ho la diarrea.','Sto sanguinando.','Sono caduto/a e mi sono ferito/a.','Ho una reazione allergica.','Prendo dei farmaci.','Ho bisogno di un medico.','Mi gira la testa.','Ho mal di schiena.'],
 pl:['Boli mnie głowa.','Boli mnie brzuch.','Boli mnie w klatce piersiowej.','Boli mnie ząb.','Mam trudności z oddychaniem.','Mam gorączkę.','Wymiotuję.','Mam biegunkę.','Krwawię.','Upadłem/am i doznałem/am urazu.','Mam reakcję alergiczną.','Przyjmuję leki.','Potrzebuję lekarza.','Mam zawroty głowy.','Bolą mnie plecy.'],
 nl:['Ik heb hoofdpijn.','Ik heb buikpijn.','Ik heb pijn op de borst.','Ik heb kiespijn.','Ik heb moeite met ademhalen.','Ik heb koorts.','Ik moet overgeven.','Ik heb diarree.','Ik bloed.','Ik ben gevallen en heb me verwond.','Ik heb een allergische reactie.','Ik gebruik medicijnen.','Ik heb een dokter nodig.','Ik ben duizelig.','Ik heb rugpijn.'],
 fr:['J’ai mal à la tête.','J’ai mal au ventre.','J’ai une douleur à la poitrine.','J’ai mal à une dent.','J’ai du mal à respirer.','J’ai de la fièvre.','Je vomis.','J’ai la diarrhée.','Je saigne.','Je suis tombé(e) et je me suis blessé(e).','J’ai une réaction allergique.','Je prends des médicaments.','J’ai besoin d’un médecin.','J’ai des vertiges.','J’ai mal au dos.'],
 ko:['머리가 아파요.','배가 아파요.','가슴에 통증이 있어요.','이가 아파요.','숨쉬기가 어려워요.','열이 있어요.','구토하고 있어요.','설사를 해요.','피가 나요.','넘어져서 다쳤어요.','알레르기 반응이 있어요.','약을 복용하고 있어요.','의사가 필요해요.','어지러워요.','허리가 아파요.'],
 bn:['আমার মাথা ব্যথা করছে।','আমার পেট ব্যথা করছে।','আমার বুকে ব্যথা হচ্ছে।','আমার দাঁতে ব্যথা করছে।','আমার শ্বাস নিতে কষ্ট হচ্ছে।','আমার জ্বর হয়েছে।','আমি বমি করছি।','আমার ডায়রিয়া হয়েছে।','আমার রক্তপাত হচ্ছে।','আমি পড়ে গিয়ে আঘাত পেয়েছি।','আমার অ্যালার্জির প্রতিক্রিয়া হচ্ছে।','আমি ওষুধ খাই।','আমার একজন ডাক্তার দরকার।','আমার মাথা ঘুরছে।','আমার পিঠে ব্যথা করছে।'],
 hi:['मेरे सिर में दर्द है।','मेरे पेट में दर्द है।','मेरे सीने में दर्द है।','मेरे दाँत में दर्द है।','मुझे साँस लेने में तकलीफ़ है।','मुझे बुखार है।','मुझे उल्टी हो रही है।','मुझे दस्त हो रहे हैं।','मेरा खून बह रहा है।','मैं गिर गया/गई और मुझे चोट लगी है।','मुझे एलर्जी की प्रतिक्रिया हो रही है।','मैं दवाएँ लेता/लेती हूँ।','मुझे डॉक्टर की ज़रूरत है।','मुझे चक्कर आ रहे हैं।','मेरी पीठ में दर्द है।'],
 es:['Me duele la cabeza.','Me duele el estómago.','Tengo dolor en el pecho.','Me duele un diente.','Tengo dificultad para respirar.','Tengo fiebre.','Estoy vomitando.','Tengo diarrea.','Estoy sangrando.','Me he caído y me he lesionado.','Tengo una reacción alérgica.','Tomo medicamentos.','Necesito un médico.','Me siento mareado/a.','Me duele la espalda.'],
 uk:['У мене болить голова.','У мене болить живіт.','У мене біль у грудях.','У мене болить зуб.','Мені важко дихати.','У мене гарячка.','Мене нудить і я блюю.','У мене діарея.','У мене кровотеча.','Я впав/впала і травмувався/травмувалася.','У мене алергічна реакція.','Я приймаю ліки.','Мені потрібен лікар.','У мене паморочиться голова.','У мене болить спина.'],
};
