import fs from 'node:fs';
const locales=['de','it','pl','nl','fr','ko','bn','hi','es','uk'];
const rows={
 hello:['Was kann ich für Sie tun? Ich bin Dagmar und bin für Sie da.','Cosa posso fare per voi? Sono Dagmar e sono qui per voi.','Co mogę dla Państwa zrobić? Jestem Dagmar i jestem tu dla Państwa.','Wat kan ik voor u doen? Ik ben Dagmar en ik sta voor u klaar.','Que puis-je faire pour vous ? Je suis Dagmar et je suis là pour vous.','무엇을 도와드릴까요? 저는 다그마르이며 여러분을 위해 여기 있습니다.','আপনার জন্য আমি কী করতে পারি? আমি দাগমার, আমি আপনাকে সাহায্য করতে এখানে আছি।','मैं आपके लिए क्या कर सकती हूँ? मैं डागमार हूँ और आपकी सहायता के लिए यहाँ हूँ।','¿Qué puedo hacer por ustedes? Soy Dagmar y estoy aquí para ayudarles.','Чим я можу Вам допомогти? Я Дагмар і я тут для Вас.'],
 guide:['Ihr Begleiter durch Prag','La vostra guida a Praga','Państwa przewodnik po Pradze','Uw gids in Praag','Votre guide de Prague','프라하 여행 안내','আপনার প্রাগ ভ্রমণের সঙ্গী','प्राग में आपकी मार्गदर्शिका','Su guía de Praga','Ваш путівник Прагою'],
 concierge:['Ihre Hotelbegleiterin','La vostra guida dell’hotel','Państwa hotelowa przewodniczka','Uw hotelgids','Votre guide de l’hôtel','호텔 여행 안내인','আপনার হোটেলের গাইড','आपकी होटल मार्गदर्शिका','Su guía del hotel','Ваша готельна гідеса'],
 home:['Willkommen','Benvenuti','Witamy','Welkom','Bienvenue','환영합니다','স্বাগতম','स्वागत है','Bienvenidos','Ласкаво просимо'],
 nearby:['Rund ums Hotel','Vicino all’hotel','W pobliżu hotelu','Rond het hotel','Autour de l’hôtel','호텔 주변','হোটেলের আশেপাশে','होटल के आसपास','Cerca del hotel','Поблизу готелю'],
 prague:['Prag entdecken','Scoprite Praga','Odkryjcie Pragę','Ontdek Praag','Découvrez Prague','프라하 둘러보기','প্রাগ আবিষ্কার করুন','प्राग की खोज करें','Descubran Praga','Відкрийте Прагу'],
 trips:['Empfohlene Ausflüge','Itinerari consigliati','Polecane wycieczki','Aanbevolen wandelingen','Balades recommandées','추천 산책 코스','প্রস্তাবিত ভ্রমণ','सुझाए गए भ्रमण','Paseos recomendados','Рекомендовані прогулянки'],
 map:['Karte erkunden','Esplorate la mappa','Odkryjcie mapę','Verken de kaart','Explorez la carte','지도 둘러보기','মানচিত্র দেখুন','नक्शा देखें','Exploren el mapa','Перегляньте мапу'],
 transport:['Öffentlicher Verkehr','Trasporti pubblici','Transport publiczny','Openbaar vervoer','Transports en commun','대중교통','গণপরিবহন','सार्वजनिक परिवहन','Transporte público','Громадський транспорт'],
 health:['Gesundheit und Notfall','Salute ed emergenze','Zdrowie i pomoc','Gezondheid en noodhulp','Santé et urgences','건강 및 응급 상황','স্বাস্থ্য ও জরুরি সহায়তা','स्वास्थ्य और आपातकाल','Salud y emergencias','Здоров’я та екстрена допомога'],
 hotel:['Ihr Hotel','Il vostro hotel','Państwa hotel','Uw hotel','Votre hôtel','호텔 안내','আপনার হোটেল','आपका होटल','Su hotel','Ваш готель'],
 welcome:['Prag wartet auf Sie.','Praga vi aspetta.','Praga czeka na Państwa.','Praag wacht op u.','Prague vous attend.','프라하가 여러분을 기다립니다.','প্রাগ আপনার অপেক্ষায় আছে।','प्राग आपकी प्रतीक्षा कर रहा है।','Praga les espera.','Прага чекає на Вас.'],
 question:['Was möchten Sie heute erleben?','Cosa vorreste fare oggi?','Co chcieliby Państwo dziś przeżyć?','Wat wilt u vandaag beleven?','Que souhaitez-vous découvrir aujourd’hui ?','오늘 무엇을 하고 싶으신가요?','আজ আপনি কী করতে চান?','आज आप क्या अनुभव करना चाहेंगे?','¿Qué les gustaría hacer hoy?','Що Ви хотіли б побачити сьогодні?'],
 inspiration:['Inspiration für heute','Un po’ di ispirazione','Inspiracja na dziś','Inspiratie voor vandaag','Un peu d’inspiration','오늘의 여행 아이디어','আজকের জন্য কিছু অনুপ্রেরণা','आज के लिए कुछ प्रेरणा','Un poco de inspiración','Натхнення на сьогодні'],
 allPlaces:['Alle Orte','Tutti i luoghi','Wszystkie miejsca','Alle plekken','Tous les lieux','모든 장소','সব স্থান','सभी स्थान','Todos los lugares','Усі місця'],
 seePlaces:['Orte entdecken','Esplorate i luoghi','Odkryjcie miejsca','Ontdek de plekken','Découvrez les lieux','장소 둘러보기','স্থানগুলি দেখুন','स्थान देखें','Exploren los lugares','Перегляньте місця'],
 discover:['Entdecken','Scopri','Odkryj','Ontdek','Découvrir','둘러보기','আবিষ্কার করুন','खोजें','Descubrir','Відкрити'],
 all:['Alles','Tutto','Wszystko','Alles','Tout','전체','সব','सभी','Todo','Усе'],
 pamatky:['Sehenswürdigkeiten','Monumenti','Zabytki','Bezienswaardigheden','Monuments','명소','দর্শনীয় স্থান','दर्शनीय स्थल','Monumentos','Пам’ятки'],
 priroda:['Natur','Natura','Przyroda','Natuur','Nature','자연','প্রকৃতি','प्रकृति','Naturaleza','Природа'],
 muzea:['Museen','Musei','Muzea','Musea','Musées','박물관','জাদুঘর','संग्रहालय','Museos','Музеї'],
 rodiny:['Mit Kindern','Con i bambini','Z dziećmi','Met kinderen','Avec les enfants','어린이와 함께','শিশুদের সঙ্গে','बच्चों के साथ','Con niños','З дітьми'],
 vyhlidky:['Aussichten','Panorami','Widoki','Uitzichten','Panoramas','전망','দৃশ্য','नज़ारे','Vistas','Краєвиди'],
 kultura:['Kultur','Cultura','Kultura','Cultuur','Culture','문화','সংস্কৃতি','संस्कृति','Cultura','Культура'],
 nakupy:['Einkaufen','Shopping','Zakupy','Winkelen','Shopping','쇼핑','কেনাকাটা','खरीदारी','Compras','Покупки'],
 sport:['Sport','Sport','Sport','Sport','Sport','스포츠','খেলাধুলা','खेल','Deporte','Спорт'],
 architektura:['Architektur','Architettura','Architektura','Architectuur','Architecture','건축','স্থাপত্য','वास्तुकला','Arquitectura','Архітектура'],
 close:['Schließen','Chiudi','Zamknij','Sluiten','Fermer','닫기','বন্ধ করুন','बंद करें','Cerrar','Закрити'],
 back:['Zurück','Indietro','Wstecz','Terug','Retour','뒤로','ফিরে যান','वापस','Volver','Назад'],
 official:['Offizielle Website','Sito ufficiale','Oficjalna strona','Officiële website','Site officiel','공식 웹사이트','অফিসিয়াল ওয়েবসাইট','आधिकारिक वेबसाइट','Sitio oficial','Офіційний сайт'],
 showMap:['Auf der Karte zeigen','Mostra sulla mappa','Pokaż na mapie','Toon op de kaart','Voir sur la carte','지도에서 보기','মানচিত্রে দেখান','नक्शे पर दिखाएँ','Ver en el mapa','Показати на мапі'],
 gallery:['Fotogalerie','Galleria fotografica','Galeria zdjęć','Fotogalerij','Galerie photo','사진 갤러리','ছবির গ্যালারি','फोटो गैलरी','Galería de fotos','Фотогалерея'],
 nextPhoto:['Nächstes Foto','Foto successiva','Następne zdjęcie','Volgende foto','Photo suivante','다음 사진','পরবর্তী ছবি','अगली फोटो','Foto siguiente','Наступне фото'],
 prevPhoto:['Vorheriges Foto','Foto precedente','Poprzednie zdjęcie','Vorige foto','Photo précédente','이전 사진','আগের ছবি','पिछली फोटो','Foto anterior','Попереднє фото'],
 hours:['Öffnungszeiten','Orari di apertura','Godziny otwarcia','Openingstijden','Horaires d’ouverture','운영 시간','খোলার সময়','खुलने का समय','Horario','Години роботи'],
 admission:['Eintritt','Ingresso','Wstęp','Toegangsprijs','Tarifs','입장료','প্রবেশমূল্য','प्रवेश शुल्क','Entrada','Вартість входу'],
 duration:['Empfohlene Besuchsdauer','Durata consigliata','Zalecany czas wizyty','Aanbevolen bezoekduur','Durée conseillée','권장 방문 시간','প্রস্তাবিত ভ্রমণের সময়','सुझाया गया समय','Duración recomendada','Рекомендована тривалість'],
 tip:['Ein Tipp von Dagmar','Un consiglio di Dagmar','Rada od Dagmar','Een tip van Dagmar','Un conseil de Dagmar','다그마르의 조언','দাগমারের পরামর্শ','डागमार की सलाह','Un consejo de Dagmar','Порада від Дагмар'],
 about:['Was Sie erwartet','Cosa vi aspetta','Co Państwa czeka','Wat u kunt verwachten','Ce qui vous attend','여행 안내','যা দেখতে পাবেন','आप क्या देखेंगे','Lo que les espera','Що на Вас чекає'],
 practical:['Planen Sie Ihren Besuch','Organizzate la visita','Zaplanujcie wizytę','Plan uw bezoek','Préparez votre visite','방문 계획','ভ্রমণের পরিকল্পনা করুন','अपनी यात्रा की योजना बनाएँ','Planifiquen la visita','Сплануйте візит'],
 updated:['Informationen geprüft','Informazioni verificate','Informacje sprawdzone','Informatie gecontroleerd','Informations vérifiées','정보 확인일','তথ্য যাচাইয়ের তারিখ','जानकारी की जाँच','Información verificada','Інформацію перевірено'],
 location:['Standort','Posizione','Lokalizacja','Locatie','Emplacement','위치','অবস্থান','स्थान','Ubicación','Розташування'],
 emergency:['Im Notfall sofort anrufen','In emergenza chiamate subito','W nagłym przypadku dzwońcie natychmiast','Bel direct bij een noodsituatie','En cas d’urgence, appelez immédiatement','응급 상황에는 즉시 전화하세요','জরুরি অবস্থায় এখনই ফোন করুন','आपातकाल में तुरंत फोन करें','En una emergencia, llamen ahora','У надзвичайній ситуації телефонуйте негайно'],
 ambulance:['Rettungsdienst','Ambulanza','Pogotowie ratunkowe','Ambulance','Ambulance','구급차','অ্যাম্বুলেন্স','एम्बुलेंस','Ambulancia','Швидка допомога'],
 euEmergency:['Europäischer Notruf','Numero di emergenza europeo','Europejski numer alarmowy','Europees alarmnummer','Numéro d’urgence européen','유럽 긴급 전화번호','ইউরোপীয় জরুরি নম্বর','यूरोपीय आपातकालीन नंबर','Número europeo de emergencias','Європейський екстрений номер'],
 emergencyNotice:['Bei Brustschmerzen, Atemnot, starken Blutungen oder Bewusstlosigkeit sofort den Rettungsdienst anrufen.','In caso di dolore al petto, difficoltà respiratorie, forte sanguinamento o perdita di coscienza, chiamate subito i soccorsi.','Przy bólu w klatce piersiowej, duszności, silnym krwawieniu lub utracie przytomności natychmiast wezwijcie pogotowie.','Bel direct de hulpdiensten bij pijn op de borst, ademhalingsproblemen, hevig bloedverlies of bewusteloosheid.','En cas de douleur thoracique, difficulté à respirer, saignement important ou perte de connaissance, appelez immédiatement les secours.','가슴 통증, 호흡 곤란, 심한 출혈 또는 의식 상실 시 즉시 응급 서비스에 전화하세요.','বুকে ব্যথা, শ্বাসকষ্ট, গুরুতর রক্তপাত বা অচেতন অবস্থায় অবিলম্বে জরুরি পরিষেবায় ফোন করুন।','सीने में दर्द, साँस लेने में तकलीफ़, गंभीर रक्तस्राव या बेहोशी होने पर तुरंत आपातकालीन सेवाओं को फोन करें।','En caso de dolor en el pecho, dificultad para respirar, hemorragia grave o pérdida de conocimiento, llamen inmediatamente a emergencias.','У разі болю в грудях, утрудненого дихання, сильної кровотечі або втрати свідомості негайно викликайте екстрену допомогу.'],
 adult:['Erwachsene','Adulti','Dorośli','Volwassenen','Adultes','성인','প্রাপ্তবয়স্ক','वयस्क','Adultos','Дорослі'],
 child:['Kinder','Bambini','Dzieci','Kinderen','Enfants','어린이','শিশু','बच्चे','Niños','Діти'],
 dental:['Zahnärztlicher Notdienst','Emergenza dentistica','Pogotowie stomatologiczne','Tandheelkundige spoedzorg','Urgences dentaires','응급 치과 진료','জরুরি দাঁতের চিকিৎসা','आपातकालीन दंत चिकित्सा','Urgencias dentales','Невідкладна стоматологія'],
 urgentHours:['Mo–Fr 19:00–06:30; Wochenenden und Feiertage durchgehend.','Lun–ven 19:00–06:30; fine settimana e festivi 24 ore su 24.','Pon–pt 19:00–06:30; weekendy i święta całodobowo.','Ma–vr 19:00–06:30; weekenden en feestdagen doorlopend.','Lun–ven 19:00–06:30 ; week-ends et jours fériés en continu.','월–금 19:00–06:30, 주말 및 공휴일 24시간.','সোম–শুক্র 19:00–06:30; সপ্তাহান্ত ও সরকারি ছুটিতে 24 ঘণ্টা।','सोम–शुक्र 19:00–06:30; सप्ताहांत और सार्वजनिक छुट्टियों पर 24 घंटे।','Lun–vie 19:00–06:30; fines de semana y festivos de forma continua.','Пн–пт 19:00–06:30; вихідні та свята цілодобово.'],
 dentalHours:['Mo–Fr 17:30–22:30; Wochenenden und Feiertage 07:30–22:30; Pause 14:00–15:00. Letzter Einlass 22:00, je nach Kapazität.','Lun–ven 17:30–22:30; fine settimana e festivi 07:30–22:30; pausa 14:00–15:00. Ultimo ingresso 22:00, secondo disponibilità.','Pon–pt 17:30–22:30; weekendy i święta 07:30–22:30; przerwa 14:00–15:00. Ostatnie przyjęcie 22:00, zależnie od liczby pacjentów.','Ma–vr 17:30–22:30; weekenden en feestdagen 07:30–22:30; pauze 14:00–15:00. Laatste aanmelding 22:00, afhankelijk van capaciteit.','Lun–ven 17:30–22:30 ; week-ends et jours fériés 07:30–22:30 ; pause 14:00–15:00. Dernière admission à 22:00, selon la capacité.','월–금 17:30–22:30, 주말 및 공휴일 07:30–22:30, 휴게 14:00–15:00. 마지막 접수 22:00, 수용 인원에 따라 조기 마감.','সোম–শুক্র 17:30–22:30; সপ্তাহান্ত ও ছুটিতে 07:30–22:30; বিরতি 14:00–15:00। শেষ রোগী গ্রহণ 22:00, স্থান থাকা সাপেক্ষে।','सोम–शुक्र 17:30–22:30; सप्ताहांत और छुट्टियाँ 07:30–22:30; विराम 14:00–15:00। अंतिम प्रवेश 22:00, क्षमता के अनुसार।','Lun–vie 17:30–22:30; fines de semana y festivos 07:30–22:30; pausa 14:00–15:00. Última admisión 22:00, según capacidad.','Пн–пт 17:30–22:30; вихідні та свята 07:30–22:30; перерва 14:00–15:00. Останній прийом 22:00, за наявності місць.'],
 symptoms:['Zeigen Sie dem Arzt Ihre Beschwerden','Indicate al medico i vostri sintomi','Powiedzcie lekarzowi, co Państwu dolega','Vertel de arts wat u voelt','Indiquez vos symptômes au médecin','의사에게 증상을 알려주세요','ডাক্তারকে আপনার উপসর্গ জানান','डॉक्टर को अपने लक्षण बताएँ','Indiquen sus síntomas al médico','Покажіть лікарю свої симптоми'],
 print:['Drucken / PDF speichern','Stampa / salva PDF','Drukuj / zapisz PDF','Afdrukken / PDF opslaan','Imprimer / enregistrer en PDF','인쇄 / PDF 저장','প্রিন্ট / PDF সংরক্ষণ','प्रिंट / PDF सहेजें','Imprimir / guardar PDF','Друк / зберегти PDF'],
 clear:['Auswahl löschen','Cancella selezione','Wyczyść wybór','Selectie wissen','Effacer la sélection','선택 지우기','নির্বাচন মুছুন','चयन हटाएँ','Borrar selección','Очистити вибір'],
 privateHealth:['Ihre Auswahl wird weder gespeichert noch versendet.','La selezione non viene salvata né inviata.','Wybór nie jest zapisywany ani wysyłany.','Uw selectie wordt niet opgeslagen of verzonden.','Votre sélection n’est ni enregistrée ni envoyée.','선택 내용은 저장되거나 전송되지 않습니다.','আপনার নির্বাচন সংরক্ষণ বা কোথাও পাঠানো হয় না।','आपका चयन सहेजा या कहीं भेजा नहीं जाता।','La selección no se guarda ni se envía.','Ваш вибір не зберігається та не надсилається.'],
 language:['Sprache','Lingua','Język','Taal','Langue','언어','ভাষা','भाषा','Idioma','Мова'],
 contact:['Rezeption anrufen','Chiama la reception','Zadzwoń do recepcji','Bel de receptie','Appeler la réception','프런트 데스크에 전화','রিসেপশনে ফোন করুন','रिसेप्शन को फोन करें','Llamar a recepción','Зателефонувати на рецепцію'],
 returnHotel:['Zurück zum Hotel','Torna all’hotel','Powrót do hotelu','Terug naar het hotel','Retour à l’hôtel','호텔로 돌아가기','হোটেলে ফিরে যান','होटल वापस जाएँ','Volver al hotel','Повернутися до готелю'],
 tickets:['Fahrkarten mit PID Lítačka','Biglietti con PID Lítačka','Bilety w PID Lítačka','Tickets met PID Lítačka','Billets avec PID Lítačka','PID Lítačka 승차권','PID Lítačka-তে টিকিট','PID Lítačka में टिकट','Billetes con PID Lítačka','Квитки у PID Lítačka'],
 connections:['Verbindung suchen','Cerca un collegamento','Znajdź połączenie','Zoek een verbinding','Rechercher un trajet','교통편 검색','সংযোগ খুঁজুন','यात्रा का मार्ग खोजें','Buscar conexión','Знайти сполучення'],
 gps:['Meinen Standort zeigen','Mostra la mia posizione','Pokaż moją lokalizację','Toon mijn locatie','Afficher ma position','내 위치 표시','আমার অবস্থান দেখান','मेरा स्थान दिखाएँ','Mostrar mi ubicación','Показати моє розташування'],
 pause:['Diashow anhalten','Pausa presentazione','Wstrzymaj pokaz','Diavoorstelling pauzeren','Mettre le diaporama en pause','슬라이드쇼 일시정지','স্লাইডশো থামান','स्लाइडशो रोकें','Pausar presentación','Призупинити показ'],
 play:['Diashow abspielen','Avvia presentazione','Uruchom pokaz','Diavoorstelling afspelen','Lancer le diaporama','슬라이드쇼 재생','স্লাইডশো চালান','स्लाइडशो चलाएँ','Iniciar presentación','Запустити показ'],
 reduced:['Animationen reduzieren','Riduci animazioni','Ogranicz animacje','Beweging verminderen','Réduire les animations','애니메이션 줄이기','অ্যানিমেশন কমান','एनिमेशन कम करें','Reducir animaciones','Зменшити анімації'],
 sound:['Dagmar sprechen lassen','Fai parlare Dagmar','Włącz głos Dagmar','Laat Dagmar spreken','Faire parler Dagmar','다그마르 음성 켜기','দাগমারের কথা শুনুন','डागमार की आवाज़ सुनें','Activar la voz de Dagmar','Увімкнути голос Дагмар'],
 mute:['Dagmar stummschalten','Silenzia Dagmar','Wycisz Dagmar','Dagmar dempen','Couper la voix de Dagmar','다그마르 음소거','দাগমারের শব্দ বন্ধ করুন','डागमार की आवाज़ बंद करें','Silenciar a Dagmar','Вимкнути голос Дагмар'],
 privacy:['Datenschutz','Privacy','Prywatność','Privacy','Confidentialité','개인정보','গোপনীয়তা','गोपनीयता','Privacidad','Конфіденційність'],
 sources:['Quellen und Bildnachweise','Fonti e crediti','Źródła i autorzy','Bronnen en credits','Sources et crédits','출처 및 저작자','সূত্র ও ছবির স্বীকৃতি','स्रोत और श्रेय','Fuentes y créditos','Джерела й автори'],
};
const all={};
for(const locale of locales){
 const p=`src/content/${locale}.json`;if(!fs.existsSync(p))continue;
 const content=JSON.parse(fs.readFileSync(p));
 for(const [key,translations]of Object.entries(rows))content.ui[key]=translations[locales.indexOf(locale)];
 all[locale]=content.ui;
 fs.writeFileSync(p,JSON.stringify(content,null,2)+'\n');
}
fs.writeFileSync('src/content/ui-translations.json',JSON.stringify(all,null,2)+'\n');
console.log('Editorial UI corrections applied:',Object.keys(all).join(', '));
