import { useEffect, useRef, useState, lazy, Suspense, type ReactNode } from 'react';
import { AnimatePresence, motion, MotionConfig, useReducedMotion } from 'motion/react';
import { Globe2, MapPin, Compass, Footprints, TrainFront, HeartPulse, Hotel, Trees, Landmark, Search, X, ChevronLeft, ChevronRight, ExternalLink, Phone, Volume2, VolumeX, Pause, Play, Printer, Check, Menu, SlidersHorizontal, LocateFixed, Accessibility, Info } from 'lucide-react';
import { languages, isLanguage, t, type Language, type UiKey } from './i18n';
import { places, trips, hotel, health, categories, placeText, tripText, photoUrl, type Place, type Photo, type MediaManifest, type Trip } from './data';
import { Restaurants, LocalServices, Transport, Faith } from './ExtraPanels';
import { te } from './extra-i18n';
import {HeritageStamp,HeritageDetails,heritagePart} from './Heritage';
import {ArrivalFromHotel} from './TouristArrival';
import { Dagmar } from './Dagmar';
import dagmarAsset from './dagmar/asset.json';
import { Utensils, HeartHandshake, Flame, Shield } from 'lucide-react';
import { symptomTranslations } from './content/symptoms';
const MapView = lazy(() => import('./MapView'));
type Screen = 'restaurants'|'faith'|'home'|'nearby'|'prague'|'trips'|'map'|'transport'|'health'|'hotel'|'404';
const screenIcons = { restaurants:Utensils, faith:HeartHandshake, home:Compass, nearby:Trees, prague:Landmark, trips:Footprints, map:MapPin, transport:TrainFront, health:HeartPulse, hotel:Hotel, '404':Compass };
const mainScreens: Screen[] = ['nearby','prague','trips','restaurants','map','transport','faith','health','hotel'];
const hints: Partial<Record<Screen,UiKey>> = {nearby:'nearbyHint',prague:'pragueHint',trips:'tripsHint',map:'mapHint',transport:'transportHint',health:'healthHint',hotel:'hotelHint'};
const screenFromPath = ():Screen => {
 const section=location.pathname.split('/')[2]||'home';
 return ['home',...mainScreens].includes(section) ? section as Screen : '404';
};
const heading=(language:Language,s:Screen)=>s==='restaurants'||s==='faith'?te(language,s):t(language,s==='404'?'notFound':s);
const hint=(language:Language,s:Screen)=>s==='restaurants'?te(language,'restaurantHint'):s==='faith'?te(language,'faithHint'):t(language,hints[s]!);
const initialLanguage = ():Language => {
 const path=location.pathname.split('/')[1];
 if(isLanguage(path)) return path;
 try {const saved=localStorage.getItem('guest-language');if(saved&&isLanguage(saved))return saved;}catch{/* preferences are optional */}
 const browser=navigator.language.split('-')[0];return isLanguage(browser)?browser:'en';
};
function External({href,children,className='button secondary'}:{href:string;children:ReactNode;className?:string}) { return <a className={className} href={href} target="_blank" rel="noopener noreferrer">{children}<ExternalLink size={16}/></a>; }
function Credit({photo}:{photo:Photo}) { return <span className="photo-credit"><a href={photo.sourceUrl} target="_blank" rel="noopener noreferrer">{photo.author}</a> · <a href={photo.licenseUrl} target="_blank" rel="noopener noreferrer">{photo.license}</a></span>; }

function Cinema({photos,language,children,compact=false}:{photos:Photo[];language:Language;children?:ReactNode;compact?:boolean}) {
 const [index,setIndex]=useState(0);const reduced=useReducedMotion();const [playing,setPlaying]=useState(!reduced);const touch=useRef(0);
 useEffect(()=>{setIndex(0);},[photos[0]?.filename]);
 useEffect(()=>{if(!playing||reduced||photos.length<2)return;const id=setInterval(()=>setIndex(i=>(i+1)%photos.length),7500);return()=>clearInterval(id);},[playing,reduced,photos.length]);
 const current=photos[index%Math.max(1,photos.length)];
 return <section className={`cinema ${compact?'compact':''}`} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{const delta=e.changedTouches[0].clientX-touch.current;if(Math.abs(delta)>55)setIndex(i=>(i+(delta<0?1:photos.length-1))%photos.length);}} aria-label={t(language,'gallery')}>
  <AnimatePresence initial={false}>{current&&<motion.img key={current.filename} src={photoUrl(current)} alt="" className="cinema-image" initial={{opacity:reduced?1:0,scale:1.04}} animate={{opacity:1,scale:playing&&!reduced?1.12:1.04}} exit={{opacity:0}} transition={{opacity:{duration:reduced?0:1.2},scale:{duration:9,ease:'linear'}}} fetchPriority={compact?'auto':'high'}/>}</AnimatePresence>
  <div className="cinema-shade"/>{children}
  {photos.length>1&&<div className="cinema-controls"><button className="glass-icon" onClick={()=>setIndex(i=>(i+photos.length-1)%photos.length)} aria-label={t(language,'prevPhoto')}><ChevronLeft size={18}/></button><div className="film-dots">{photos.map((p,i)=><button key={p.filename} className={i===index?'active':''} onClick={()=>setIndex(i)} aria-label={`${t(language,'photo')} ${i+1}`} aria-pressed={i===index}/>)}</div><button className="glass-icon" onClick={()=>setIndex(i=>(i+1)%photos.length)} aria-label={t(language,'nextPhoto')}><ChevronRight size={18}/></button><button className="glass-icon" onClick={()=>setPlaying(p=>!p)} aria-label={t(language,playing?'pause':'play')}>{playing?<Pause size={16}/>:<Play size={16}/>}</button></div>}
  {current&&<Credit photo={current}/>}<span className="film-corner top-left" aria-hidden="true"/><span className="film-corner bottom-right" aria-hidden="true"/>
 </section>;
}

export function App() {
 const [language,setLanguage]=useState<Language>(initialLanguage);const [screen,setScreen]=useState<Screen>(screenFromPath);
 const [media,setMedia]=useState<Photo[]>([]);const [selectedPlace,setSelectedPlace]=useState<string|null>(new URLSearchParams(location.search).get('place'));
 const [trip,setTrip]=useState<Trip|null>(null);const [search,setSearch]=useState('');const [category,setCategory]=useState('all');
 const [mapTarget,setMapTarget]=useState<string|null>(null);const [healthSelection,setHealthSelection]=useState<string[]>([]);
 const [medicalNotes,setMedicalNotes]=useState({onset:'',allergies:'',medicines:''});const [voiceError,setVoiceError]=useState(false);
 const [speaking,setSpeaking]=useState(false);const [menu,setMenu]=useState(false);const [busy,setBusy]=useState(false);
 const [reduced,setReduced]=useState(false);const [info,setInfo]=useState<'privacy'|'credits'|null>(null);
 const dialogRef=useRef<HTMLDialogElement>(null);const infoRef=useRef<HTMLDialogElement>(null);const systemReduced=useReducedMotion();
 const getPhotos=(id:string)=>media.filter(p=>p.placeId===id);
 const currentPlace=places.find(p=>p.id===selectedPlace);
 useEffect(()=>{fetch('/media/manifest.json').then(r=>{if(!r.ok)throw Error();return r.json();}).then((m:MediaManifest)=>setMedia(m.photos)).catch(()=>setMedia([]));
  try{setReduced(localStorage.getItem('guest-motion')==='reduce');}catch{/* preferences are optional */}
 },[]);
 useEffect(()=>{
  document.documentElement.lang=language;
  document.title=`Dagmar · ${heading(language,screen)} · Hotel CHODOV ASC`;
  document.querySelector('meta[name="description"]')?.setAttribute('content',t(language,'intro'));
  const path=`/${language}/${screen==='home'?'':screen+'/'}${selectedPlace?'?place='+encodeURIComponent(selectedPlace):''}`;
  let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.append(canonical);}canonical.href='https://guest.hcasc.cz'+path;
  document.querySelectorAll<HTMLLinkElement>('link[rel="alternate"][hreflang]').forEach(link=>{const lang=link.hreflang==='x-default'?'cs':link.hreflang;link.href=`https://guest.hcasc.cz/${lang}/${screen==='home'?'':screen+'/'}${selectedPlace?'?place='+encodeURIComponent(selectedPlace):''}`;});
  const nextPath=`/${language}/${screen==='home'?'':screen+'/'}${selectedPlace?'?place='+encodeURIComponent(selectedPlace):''}`;
  history.replaceState(null,'',nextPath);
  try{localStorage.setItem('guest-language',language);}catch{/* preferences are optional */}
 },[language,screen,selectedPlace]);
 useEffect(()=>{const onPop=()=>{const lang=location.pathname.split('/')[1];if(isLanguage(lang))setLanguage(lang);setScreen(screenFromPath());setSelectedPlace(new URLSearchParams(location.search).get('place'));};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
 useEffect(()=>{if(currentPlace){dialogRef.current?.showModal();}else{dialogRef.current?.close();}},[currentPlace]);
 useEffect(()=>{if(info)infoRef.current?.showModal();else infoRef.current?.close();},[info]);
 const navigate=(next:Screen,target?:string)=>{
  if(next===screen&&!target){setMenu(false);return;}
  setBusy(true);setMenu(false);setTrip(null);setSelectedPlace(null);
  if(target)setMapTarget(target);
  history.pushState(null,'',`/${language}/${next==='home'?'':next+'/'}${target&&next!=='map'?'?place='+target:''}`);
  setScreen(next);window.scrollTo({top:0,behavior:'instant'});setTimeout(()=>setBusy(false),850);
 };
 const openPlace=(id:string)=>{if(id==='hotel')navigate('hotel');else setSelectedPlace(id);};
 const message=screen==='home'?t(language,'hello'):screen==='health'?t(language,'healthIntro'):screen==='transport'?t(language,'transportIntro'):screen==='hotel'?t(language,'hotelIntro'):screen==='trips'?t(language,'tripIntro'):screen==='restaurants'?te(language,'restaurantHint'):screen==='faith'?te(language,'faithHint'):t(language,'intro');
 const renderCards=(items:Place[])=>items.map((place,i)=><motion.button key={place.id} className="place-card" onClick={()=>openPlace(place.id)} initial={reduced||systemReduced?false:{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true,margin:'60px'}} transition={{delay:Math.min(i*.04,.2),duration:.4}}>
  <div className="place-image">{getPhotos(place.id)[0]&&<img src={photoUrl(getPhotos(place.id)[0])} alt="" loading="lazy"/>}<span className="place-category">{t(language,place.category as UiKey)}</span><span className="photo-count">{getPhotos(place.id).length} <span>◉</span></span><HeritageStamp id={place.id} language={language}/></div>
  <div className="place-copy"><span className="place-duration"><Footprints size={14}/>{place.visitDuration}</span><h3>{placeText(language,place.id).name}</h3><p>{placeText(language,place.id).short}</p><span className="card-discover">{t(language,'discover')}<Compass size={16}/></span></div>
 </motion.button>);
 const filtered=places.filter(p=>(screen!=='nearby'||p.area==='okoli')&&(screen!=='prague'||p.area==='praha')&&(category==='all'||(category==='unesco'?!!heritagePart(p.id):p.category===category))&&((placeText(language,p.id).name+' '+placeText(language,p.id).description).normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase(language).includes(search.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase(language))));
 const heroPhotos=['karluv-most','prazsky-hrad','letenske-sady','pruhonicky-park'].flatMap(id=>getPhotos(id).slice(0,1));
 return <MotionConfig reducedMotion={reduced?'always':'user'}><div className={`app ${reduced||systemReduced?'reduce-motion':''}`}>
  <a className="skip" href="#main">{t(language,'skip')}</a>
  <header className="site-header"><button className="brand" onClick={()=>navigate('home')} aria-label="Hotel CHODOV ASC"><img src="/logo.png" alt="Hotel CHODOV ASC" width="1181" height="846"/><span><strong>HOTEL CHODOV <span>ASC</span></strong><small>{t(language,'guide')}</small></span></button>
   <nav className="desktop-nav" aria-label={t(language,'guide')}>{(['home','prague','trips','hotel'] as Screen[]).map(s=><button key={s} className={screen===s?'current':''} onClick={()=>navigate(s)}>{heading(language,s)}</button>)}</nav>
   <div className="header-actions"><label className="language-select"><Globe2 size={17}/><span className="sr-only">{t(language,'language')}</span><select aria-label={t(language,'language')} value={language} onChange={e=>setLanguage(e.target.value as Language)}>{languages.map(l=><option key={l.code} value={l.code}>{l.label}</option>)}</select></label><button className="icon-button menu-button" onClick={()=>setMenu(m=>!m)} aria-expanded={menu} aria-label={t(language,'allPlaces')}>{menu?<X size={22}/>:<Menu size={22}/>}</button></div>
  </header>
  <AnimatePresence>{menu&&<motion.nav className="mobile-menu" initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}}>{(['home',...mainScreens] as Screen[]).map(s=>{const Icon=screenIcons[s];return <button key={s} onClick={()=>navigate(s)}><Icon size={19}/>{heading(language,s)}</button>;})}</motion.nav>}</AnimatePresence>
  <main id="main" tabIndex={-1}>
   {screen==='home'?<>
    <Cinema photos={heroPhotos} language={language}><div className="hero-copy"><span className="eyebrow"><span/>HOTEL CHODOV ASC · PRAHA</span><h1>{t(language,'welcome')}</h1><p>{t(language,'intro')}</p><button className="button light" onClick={()=>navigate('prague')}><Compass size={18}/>{t(language,'seePlaces')}</button></div><div className="scene-number" aria-hidden="true">01 <span>/ PRAHA</span></div></Cinema>
    <div className="home-content"><Dagmar language={language} message={message} busy={busy} reduced={reduced||!!systemReduced} voiceEnabled={speaking} onVoiceChange={setSpeaking} onVoiceError={setVoiceError}/><div className="section-heading"><div><span className="eyebrow dark">DAGMAR · {t(language,'guide')}</span><h2>{t(language,'question')}</h2></div><span className="fine-mark" aria-hidden="true">✦</span></div>
     <div className="home-sos"><span>{t(language,'emergency')}</span><a href="tel:112"><Phone size={17}/>112</a><button onClick={()=>navigate('health')}><HeartPulse size={17}/>{t(language,'health')}</button></div><div className="choices">{mainScreens.map((s,i)=>{const Icon=screenIcons[s];return <button key={s} className={`choice ${s==='health'?'health-choice':''}`} onClick={()=>navigate(s)}><span className="choice-icon"><Icon size={23} strokeWidth={1.6}/></span><span className="choice-text"><strong>{heading(language,s)}</strong><small>{hint(language,s)}</small></span><span className="choice-number">0{i+1}</span></button>;})}</div>
     <div className="section-heading inspiration-heading"><div><span className="eyebrow dark">PRAHA</span><h2>{t(language,'inspiration')}</h2></div><button className="text-button" onClick={()=>navigate('prague')}>{t(language,'allPlaces')}<Compass size={17}/></button></div><div className="places-grid inspiration-grid">{renderCards(places.filter(p=>['karluv-most','pruhonicky-park','narodni-technicke-muzeum'].includes(p.id)))}</div>
    </div>
   </>:<><div className="page-top"><button className="text-button" onClick={()=>navigate('home')}><ChevronLeft size={18}/>{t(language,'home')}</button><Dagmar language={language} message={message} busy={busy} small reduced={reduced||!!systemReduced} voiceEnabled={speaking} onVoiceChange={setSpeaking} onVoiceError={setVoiceError}/><h1>{heading(language,screen)}</h1></div>
   <AnimatePresence mode="wait"><motion.div key={screen} className="page-content" initial={reduced||systemReduced?false:{opacity:0,y:18,clipPath:'inset(0 0 12% 0)'}} animate={{opacity:1,y:0,clipPath:'inset(0 0 0% 0)'}} exit={{opacity:0,y:-12}} transition={{duration:reduced||systemReduced?0:.5}}>
    {(screen==='nearby'||screen==='prague')&&<>{screen==='nearby'&&<LocalServices language={language}/>}<div className="catalog-tools"><label className="search"><Search size={20}/><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder={t(language,'search')} aria-label={t(language,'search')}/>{search&&<button className="icon-button" aria-label={t(language,'reset')} onClick={()=>setSearch('')}><X size={18}/></button>}</label><div className="filter-chips"><button onClick={()=>setCategory('all')} className={category==='all'?'active':''} aria-pressed={category==='all'}>{t(language,'all')}</button><button onClick={()=>setCategory('unesco')} className={category==='unesco'?'active':''} aria-pressed={category==='unesco'}>UNESCO</button>{categories.filter(c=>places.some(p=>p.category===c&&(screen==='nearby'?p.area==='okoli':p.area==='praha'))).map(c=><button key={c} onClick={()=>setCategory(c)} className={category===c?'active':''} aria-pressed={category===c}>{t(language,c)}</button>)}</div></div><p className="results-count">{filtered.length} {t(language,'results')}</p><div className="places-grid">{renderCards(filtered)}</div>{filtered.length===0&&<div className="empty-state"><Search size={32}/><p>{t(language,'noResults')}</p><button className="button" onClick={()=>{setSearch('');setCategory('all');}}>{t(language,'reset')}</button></div>}</>}
    {screen==='trips'&&<div className="trips-grid">{trips.map((r,i)=><button key={r.id} className={`trip-card ${trip?.id===r.id?'selected':''}`} onClick={()=>setTrip(trip?.id===r.id?null:r)} aria-expanded={trip?.id===r.id}><div className="trip-photo">{getPhotos(r.stopIds[0])[0]&&<img src={photoUrl(getPhotos(r.stopIds[0])[0])} alt="" loading="lazy"/>}<span className="trip-order">0{i+1}</span></div><div className="trip-copy"><span className="eyebrow dark"><Footprints size={14}/> {r.stopIds.length} {t(language,'stops')}</span><h2>{tripText(language,r.id).name}</h2><p>{tripText(language,r.id).notes}</p></div></button>)}{trip&&<section className="itinerary"><div className="section-heading"><h2>{t(language,'itinerary')}</h2><button className="icon-button" aria-label={t(language,'close')} onClick={()=>setTrip(null)}><X size={20}/></button></div><p><strong>{t(language,'starting')}: </strong>{tripText(language,trip.id).start}</p><ol>{trip.stopIds.map(id=><li key={id}><button onClick={()=>openPlace(id)}>{placeText(language,id).name}<MapPin size={18}/></button></li>)}</ol><p className="notice"><Info size={18}/>{t(language,'routeNotice')}</p></section>}</div>}
    {screen==='map'&&<Suspense fallback={<p className="loading">{t(language,'mapLoading')}</p>}><MapView language={language} target={mapTarget} onPlace={openPlace}/></Suspense>}
    {screen==='restaurants'&&<Restaurants language={language}/>}
    {screen==='transport'&&<Transport language={language}/>}
    {screen==='faith'&&<Faith language={language}/>}
    {screen==='health'&&<div className="health-page"><section className="emergency-card"><div><span className="eyebrow">{t(language,'emergency')}</span><h2>{t(language,'health')}</h2><p>{t(language,'emergencyNotice')}</p></div><div className="emergency-phones"><a href="tel:155"><Phone size={26}/><strong>155</strong><span>{t(language,'ambulance')}</span></a><a href="tel:112"><Phone size={26}/><strong>112</strong><span>{t(language,'euEmergency')}</span></a></div></section>
     <div className="other-emergency">{([{number:'158',key:'police',Icon:Shield},{number:'150',key:'fire',Icon:Flame},{number:'156',key:'municipal',Icon:Shield}] as const).map(({number,key,Icon})=><a key={number} href={`tel:${number}`}><Icon size={24}/><strong>{number}</strong><span>{te(language,key)}</span></a>)}</div>
     <section className="hospital-card"><div className="section-heading"><div><span className="eyebrow dark">{t(language,'hospitalTitle')}</span><h2>{t(language,'hospitalName')}</h2><p>Vídeňská 800, 140 59 Praha 4 – Krč</p><p>{t(language,'pavilion')}</p></div><HeartPulse size={42} strokeWidth={1.3}/></div><div className="hospital-services">{(['adult','child','dental'] as const).map(kind=><div key={kind}><h3>{t(language,kind)}</h3><a href={`tel:+420${health.hospital[kind].phone.replace(/\s/g,'')}`}><Phone size={16}/>+420 {health.hospital[kind].phone}</a><a className="alt-phone" href={`tel:+420${health.hospital[kind].alt.replace(/\s/g,'')}`}>+420 {health.hospital[kind].alt}</a><p>{t(language,kind==='dental'?'dentalHours':'urgentHours')}</p></div>)}</div><div className="button-row"><External href={health.hospital.source}>{t(language,'hospitalOfficial')}</External><External href="https://www.google.com/maps/dir/?api=1&destination=Fakultn%C3%AD+Thomayerova+nemocnice%2C+V%C3%ADde%C5%88sk%C3%A1+800%2C+Praha&travelmode=driving">{t(language,'carRoute')}</External><a className="text-button" href="tel:+420261081111"><Phone size={16}/>{t(language,'switchboard')} +420 261 081 111</a></div><p className="metadata">{t(language,'updated')}: 08.10.2026</p></section>
     <section className="symptoms-section"><div className="section-heading"><div><h2>{t(language,'symptoms')}</h2><p>{t(language,'symptomHint')}</p></div><button className="button secondary" onClick={()=>window.print()}><Printer size={18}/>{t(language,'print')}</button></div><div className="symptom-grid">{health.symbols.map((s,i)=><button className={`symptom ${healthSelection.includes(s.id)?'selected':''}`} key={s.id} onClick={()=>setHealthSelection(ids=>ids.includes(s.id)?ids.filter(id=>id!==s.id):[...ids,s.id])} aria-pressed={healthSelection.includes(s.id)}><span className="symptom-icon" aria-hidden="true">{s.icon}</span><span><strong>{symptomTranslations[language][i]}</strong>{language!=='cs'&&<small lang="cs">{s.cs}</small>}</span><span className="symptom-check">{healthSelection.includes(s.id)&&<Check size={17}/>}</span></button>)}</div><fieldset className="medical-notes"><legend>{te(language,'medicalNotes')}</legend>{(['onset','allergies','medicines'] as const).map(key=><label key={key}>{te(language,key)}{language!=='cs'&&<small lang="cs">{te('cs',key)}</small>}<input value={medicalNotes[key]} maxLength={180} autoComplete="off" onChange={e=>setMedicalNotes(n=>({...n,[key]:e.target.value}))}/></label>)}</fieldset><div className="selection-bar"><span>{healthSelection.length} {t(language,'selected')}</span><button className="text-button" onClick={()=>setHealthSelection([])}>{t(language,'clear')}</button></div><p className="privacy-note">{t(language,'privateHealth')}</p></section>
     <section className="print-card" aria-label={t(language,'healthCard')}><img src="/logo.png" alt="Hotel CHODOV ASC"/><h2>{t(language,'healthCard')}</h2><p>{t(language,'doctorLanguage')}</p><p>155 · 112 | {hotel.address}</p><ul>{health.symbols.filter(s=>healthSelection.length===0||healthSelection.includes(s.id)).map(s=><li key={s.id}><strong>{symptomTranslations[language][health.symbols.indexOf(s)]}</strong><span lang="cs">{s.cs}</span></li>)}</ul><dl className="printed-notes">{(['onset','allergies','medicines'] as const).map(key=><div key={key}><dt>{te(language,key)} / <span lang="cs">{te('cs',key)}</span></dt><dd>{medicalNotes[key]||'________________________________'}</dd></div>)}</dl><p>Fakultní Thomayerova nemocnice · Vídeňská 800, Praha 4 · +420 261 081 111</p><p>{t(language,'updated')}: 08.10.2026</p></section></div>}
    {screen==='hotel'&&<section className="hotel-card"><div className="hotel-identity"><img src="/logo.png" alt="Hotel CHODOV ASC"/><span className="eyebrow dark">{t(language,'hotel')}</span><h2>Hotel CHODOV ASC</h2><p>{t(language,'hotelIntro')}</p><figure className="hotel-qr"><img src="/guest-qr.png" alt={t(language,'guide')} width="330" height="330"/><figcaption>guest.hcasc.cz</figcaption></figure></div><div className="hotel-information"><div><span>{t(language,'address')}</span><h3>{hotel.address}</h3></div><div><span>{t(language,'phone')}</span><a href="tel:+420608877424">+420 608 877 424</a></div><div className="button-row"><a className="button" href="tel:+420608877424"><Phone size={18}/>{t(language,'contact')}</a><button className="button secondary" onClick={()=>navigate('map','hotel')}><MapPin size={18}/>{t(language,'hotelMap')}</button><External href={hotel.url}>{t(language,'hotelOfficial')}</External></div><p className="notice"><Info size={18}/>{t(language,'entranceNotice')}</p></div></section>}
    {screen==='404'&&<div className="empty-state"><Compass size={50}/><p>{t(language,'notFoundHint')}</p><button className="button" onClick={()=>navigate('home')}>{t(language,'home')}</button></div>}
   </motion.div></AnimatePresence></>}
  </main>
  <footer><div className="footer-brand"><img src="/logo.png" alt="Hotel CHODOV ASC"/><span>HOTEL CHODOV ASC<small>{t(language,'copyright')}</small></span></div><div className="footer-tools"><button onClick={()=>{setSpeaking(v=>!v);}} title={t(language,'speakHint')}>{speaking?<Volume2 size={17}/>:<VolumeX size={17}/>}<span>{t(language,speaking?'mute':'sound')}</span></button><button onClick={()=>{setReduced(v=>!v);try{localStorage.setItem('guest-motion',reduced?'full':'reduce');}catch{/* preferences are optional */}}} aria-pressed={reduced}><Accessibility size={17}/><span>{t(language,reduced?'motion':'reduced')}</span></button><button onClick={()=>setInfo('privacy')}>{t(language,'privacy')}</button><button onClick={()=>setInfo('credits')}>{t(language,'sources')}</button></div>{voiceError&&<p role="status" className="voice-status">{te(language,'voicesUnavailable')}</p>}<small className="release-tag">09.10.2026 · {__RELEASE_SHA__}</small></footer>
  <nav className="bottom-nav" aria-label={t(language,'guide')}>{(['home','prague','map','health','hotel'] as Screen[]).map(s=>{const Icon=screenIcons[s];return <button key={s} className={screen===s?'active':''} onClick={()=>navigate(s)} aria-current={screen===s?'page':undefined}><Icon size={20}/><span>{heading(language,s)}</span></button>;})}</nav>
  <dialog ref={dialogRef} className="place-dialog" onCancel={()=>setSelectedPlace(null)} onClick={e=>{if(e.target===dialogRef.current)setSelectedPlace(null);}}>
   {currentPlace&&<div className="detail-shell"><button className="dialog-close icon-button" aria-label={t(language,'close')} onClick={()=>setSelectedPlace(null)}><X size={23}/></button><Cinema photos={getPhotos(currentPlace.id)} language={language} compact><div className="detail-hero-copy"><span className="eyebrow">{t(language,currentPlace.category as UiKey)}</span><h2>{placeText(language,currentPlace.id).name}</h2></div></Cinema><div className="detail-content"><label className="language-select dialog-language"><Globe2 size={17}/><span>{t(language,'language')}</span><select aria-label={t(language,'language')} value={language} onChange={e=>setLanguage(e.target.value as Language)}>{languages.map(l=><option key={l.code} value={l.code}>{l.label}</option>)}</select></label><HeritageDetails id={currentPlace.id} language={language}/><p className="detail-intro">{placeText(language,currentPlace.id).short}</p><h3>{t(language,'about')}</h3><p>{placeText(language,currentPlace.id).description}</p><div className="dagmar-tip"><img src={dagmarAsset.poster.url} alt="Dagmar"/><div><h3>{t(language,'tip')}</h3><p>{placeText(language,currentPlace.id).tip}</p></div></div><h3>{t(language,'practical')}</h3><dl className="practical"><div><dt>{t(language,'hours')}</dt><dd>{placeText(language,currentPlace.id).hours}</dd></div><div><dt>{t(language,'admission')}</dt><dd>{placeText(language,currentPlace.id).admission}</dd></div><div><dt>{t(language,'duration')}</dt><dd>{currentPlace.visitDuration}</dd></div></dl><p className="metadata">{t(language,'updated')}: {currentPlace.verifiedOn}</p><p className="notice">{t(language,'changeNotice')}</p><div className="button-row"><External href={currentPlace.officialUrl} className="button">{t(language,'official')}</External><button className="button secondary" onClick={()=>navigate('map',currentPlace.id)}><MapPin size={18}/>{t(language,'showMap')}</button></div><ArrivalFromHotel id={currentPlace.id} language={language}/><h3>{t(language,'location')}</h3><p className="metadata">{currentPlace.lat.toFixed(6)}, {currentPlace.lon.toFixed(6)}</p><p>{placeText(language,currentPlace.id).coordinateNote}</p><p className="notice">{t(language,currentPlace.needsEntranceCoordinatesVerification?'entranceNotice':'entranceVerified')}</p><details className="credits-details"><summary>{t(language,'credits')}</summary>{getPhotos(currentPlace.id).map(p=><p key={p.filename}><Credit photo={p}/></p>)}</details></div></div>}
  </dialog>
  <dialog ref={infoRef} className="info-dialog" onCancel={()=>setInfo(null)}><button className="icon-button" aria-label={t(language,'close')} onClick={()=>setInfo(null)}><X size={22}/></button><h2>{t(language,info==='credits'?'sources':'privacy')}</h2>{info==='privacy'?<p>{t(language,'privacyText')}</p>:<><p>{te(language,'resizedPhotos')}</p><p>© OpenStreetMap · Protomaps · Natural Earth</p><p>Rain Rig (CC) Blender Foundation | <a href="https://studio.blender.org/characters/rain/v3/" target="_blank" rel="noopener noreferrer">studio.blender.org</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">CC BY 4.0</a> · {te(language,'characterAdaptation')}</p><p>Dagmar: Hotel CHODOV ASC · <a href="https://quaternius.com/packs/universalanimationlibrary.html" target="_blank" rel="noopener noreferrer">Quaternius</a> · <a href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener noreferrer">CC0 1.0</a></p><p>OpenAI image generation · 08.10.2026</p>{media.map(p=><p key={p.filename}><span>{placeText(language,p.placeId).name}: </span><Credit photo={p}/></p>)}</>}</dialog>
 </div></MotionConfig>;
}
